# https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:10040"
moniker = ""
fast_sync = true

db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:8040"

[consensus]
create_empty_blocks_interval = 15

[tx_index]
index_all_tags = true

[p2p]
max_num_peers = 300
pex = false
laddr = "tcp://127.0.0.1:9040"
# sentry names: sentry-a, sentry-b
seeds = "127.0.0.1:9030"
